version: 2.1

jobs:
  pythonTests:
    executor: python-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Generate cache seeds"
          command: find . -name poetry.lock | sort | xargs md5sum > /tmp/checksums
      - restore_cache:
          key: deps-3-{{ checksum "/tmp/checksums" }}
      - run:
          command: pwd && ls
      - run:
          name: "Install deps"
          command: pip install --user poetry==1.0.0 && poetry install
      - save_cache:
          key: deps-3-{{ checksum "/tmp/checksums" }}
          paths:
            - "/root/.cache/pypoetry/virtualenvs"
      - run:
          name: "PyTest"
          command: |
            poetry run coverage run --source . -m pytest -vv
            poetry run coverage report
            poetry run coverage html
      - store_test_results:
          path: test-reports
          prefix: tests
      - store_artifacts:
          path: htmlcov

  runHooks:
    executor: python-build
    steps:
      - checkout
      - run:
          name: "Install pre-commit"
          command: pip install pre-commit --user
      - run: pre-commit run -a -c .pre-commit-config.ci.yaml

  mypy:
    executor: python-build
    steps:
      - checkout
      - run:
          name: "Generate cache seeds"
          command: find . -name poetry.lock | sort | xargs md5sum > /tmp/checksums
      - restore_cache:
          key: deps-3-{{ checksum "/tmp/checksums" }}
      - run:
          name: "Install deps"
          command: pip install --user poetry==1.0.0 && poetry install
      - save_cache:
          key: deps-3-{{ checksum "/tmp/checksums" }}
          paths:
            - "/root/.local/share/virtualenvs"
      - run:
          name: "mypy"
          command: poetry run mypy bento
      - store_test_results:
          path: test-reports
          prefix: tests
      - store_artifacts:
          path: test-reports

  runAcceptance:
    executor: python-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Generate cache seeds"
          command: find . -name poetry.lock | sort | xargs md5sum > /tmp/checksums
      - restore_cache:
          key: deps-3-{{ checksum "/tmp/checksums" }}
      - run:
          name: "Install deps"
          command: pip install --user poetry==1.0.0 && poetry install
      - save_cache:
          key: deps-3-{{ checksum "/tmp/checksums" }}
          paths:
            - "/root/.cache/pypoetry/virtualenvs/virtualenvs"
      - run:
          name: "QA Tests"
          command: make qa-test

  envAcceptance:
    executor: python-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Python 3.6 Tests"
          command: make env-test

  bentoRun:
    working_directory: ~/circleci
    executor: python-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: "Configure poetry"
          command: pip install --user poetry==1.0.0 && poetry install
      - run:
          name: "Make bento"
          command: poetry run make -B build && poetry run bento --version --agree
      - run:
          name: "Install react"
          command: (cd tests/integration/react && npm install)
      - run:
          name: "Running bento check"
          command: poetry run bento --agree --email test@returntocorp.com check --no-pager --all 2>&1 | cat
      - store_artifacts:
          path: "/home/circleci/.bento/last.log"

workflows:
  build-and-deploy:
    jobs:
      - pythonTests
      - runHooks
      - mypy
      - runAcceptance
      - envAcceptance
      - bentoRun

executors:
  python-build:
    working_directory: ~/circleci
    docker:
      - image: circleci/python:3.7.4-stretch-node
